//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labentry
{
    using System;
    using System.Collections.Generic;
    
    public partial class labform
    {
        public string accessionno { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string address { get; set; }
        public System.DateTime dateofbirth { get; set; }
        public int age { get; set; }
        public string gender { get; set; }
        public string requisitionerlastname { get; set; }
        public string requisitionerfirstname { get; set; }
        public string requisitionerunit { get; set; }
        public string requisitionerphone { get; set; }
        public string requisitionermobile { get; set; }
        public string requisitioneremail { get; set; }
        public string requisitionerfax { get; set; }
        public string labexamname { get; set; }
        public System.DateTime labexamcollecteddatetime { get; set; }
        public string labexamcollectedby { get; set; }
        public string clinicalimpression { get; set; }
        public string suspectedagent { get; set; }
        public Nullable<System.DateTime> specimenreceivedatetime { get; set; }
        public string specimenreceivedby { get; set; }
        public string specimenttype { get; set; }
        public string specimentfacility { get; set; }
        public Nullable<System.DateTime> illnessonsetdatetime { get; set; }
        public Nullable<System.DateTime> specimencollecteddatetime { get; set; }
        public string result { get; set; }
        public Nullable<System.DateTime> resultdatetime { get; set; }
    }
}
